### ISSUE TITLE
I had this error when I tried to run the example in python: {"error":{"code":-32102,"message":"You have no access rights to the Application."},"id":5,"jsonrpc":"2.0"}, and when I approve the access, I had this one: {"error":{"code":-32019,"message":"Session limit on this device has been reached."},"id":8,"jsonrpc":"2.0"}

### ISSUE THREAD

**Issue by datronica** [Emotiv/cortex-v2-example#49] opened 2019-11-05 16:21 UTC

**Comment by nguoithichkhampha** [comment] 2019-11-19 16:03
Duplicate of #42

**Closed** 2019-11-19 16:03 UTC
